hydra:
  run:
    #dir:  /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/algo_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/algo_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep: 
    dir: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/algo_configs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

StairDetector:
  enable: false
  blur:
    enable: true
    type: 1
  GaussianBlur:
    ksize: 15
    sigmaX: 3
    sigmaY: 3
  Gabor:
    ksize: 7
    sigma: 1.6
    theta: 90
    lambd: 5
    gamma: 1
    psi: 9.5
  Bilateral:
    d: 5
    sigmaColor: 30
    sigmaSpace: 20
  Sobel:
    enable: true
    ksize: 11
    thresh: 100
  Canny:
    enable: true
    thresh1: 100
    thresh2: 250
    aperture: 3
  HoughLinesP:
    minLineLength: 100
    maxLineGap: 3
    rho: 1
    theta: 180
    thresh: 10
  Eliminate:
    top_bottom: [20,320] # [top,bottom]
    sides: [440,200] # [right, left]
    theta: 15
    depth: [0.3,2] # [close lim, far lim]

NormalEstimation: null

AlgoRunner:
  video:
    debug: true
    save: false
    name: rgb_vid
  
  plots:
    debug:
      online: false
      offline: true
    save_mode: false
    name: default

  run_from: null
  save_run: false

  AnalyticEnvRecognition:
    static_thresholds:
    - 0.3
    - 2
    dynamic_thresholds:
      sa: -4
      sd: 4
