hydra:
  run:
    #dir:  /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/algo_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/algo_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}

StairDetector:

  blur:
    enable: true
    type: 1         # 0 = gaussian | 1 = gabor | bilateral = 2
        

  Sobel:
    enable: true
    ksize: 9
    thresh: 100  
  
  GaussianBlur:
    ksize: 9
    sigmaX: 3
    sigmaY: 3

  Gabor: 
    ksize: 5
    sigma: 1
    theta: 90
    lambd: 5
    gamma: 1
    psi: 7.8

  Bilateral:
      d: 5
      sigmaColor: 30
      sigmaSpace: 20

  Canny:
    enable: True  
    thresh1: 20
    thresh2: 150
    aperture: 3

  HoughLinesP:
    minLineLength: 100
    maxLineGap: 5
    rho: 1
    theta: 120
    thresh: 0

  Eliminate:
    top: 15
    bottom: 220
    theta: 20
    depth: 0.3


NormalEstimation: # TO DO
  
AlgoRunner:
  save_run: False
  
  IntentRecognition:
    static_thresholds: [0.08,0.95]
    dynamic_thresholds:
      sa: -2.5
      sd: 2.5

