
hydra:
  run:
    #dir:  /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #dir: ./conf/recorder/records_configs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    #dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/rate:${recorder.rate}


topics:
  tf: "/tf"
  imu: "/zedm/zed_node/imu/data"
  rgb: "/zedm/zed_node/rgb/image_rect_color"
  depth: "/zedm/zed_node/depth/depth_registered"
  confidence: "/zedm/zed_node/confidence/confidence_map"


recording:
  script: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/scripts/brings_up/record_zed.sh #/home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/scripts/brings_up/record_zed.sh
  bag_folder: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/bag #/home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/bag
  rec_imu : True
  rec_rgb : True
  rec_depth : True
  rec_tf : True
  rec_confidence: True