
hydra:
  run:
    dir:  /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #dir: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #dir: ./conf/recorder/records_configs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    #dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/rate:${recorder.rate}


topics:
  tf: /tf
  imu: /zedm/zed_node/imu/data
  rgb: /zedm/zed_node/rgb/image_rect_color
  depth: /zedm/zed_node/depth/depth_registered
  confidence: /zedm/zed_node/confidence/confidence_map
  disparity: /zedm/zed_node/disparity/disparity_image
  odom: /zedm/zed_node/odom
  pointcloud: /zedm/zed_node/point_cloud/cloud_registered


recording:
  script: /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/scripts/brings_up/record_zed.sh
  #script: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/scripts/brings_up/record_zed.sh
  bag_folder: /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/bag
  #bag_folder: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/bag
  #camera_params_fodler: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}/camera_params
  camera_params_fodler: /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}/camera_params  
  rec_imu : False
  rec_rgb : False
  rec_depth : False
  rec_tf : False
  rec_confidence: False
  rec_disparity: False
  rec_pointcloud: True
  rec_odom : False

